name: Trigger Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render deployment
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d1bgh76uk2gs739ork20?key=$RENDER_API_KEY" \
             -H "Accept: application/json"git 
             
          